version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - agriness-db
    env_file:
      - ./.env

  agriness-db:
    image: postgres
    ports:
       - "5434:5432"
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
